import java.util.Scanner;

class Lecture01 {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        System.out.println("\n Hello from lecture 01");
    
    

        // SELF-CHECK PROBLEMS:
        // Note: you may need to put some of your answers inside comments

//       Put your answer for #1 here:
//        Answer: The program prints "Hello from lecture 01" to the console when it is executed.
//      This output is generated by the System.out.println() statement in the main method.

//      Where in the textbook are the main topics for this question covered?
//           Answer: You can find this in chapter 1 page pg:120

        //
        // Copy and paste the output from when you first cloned (downloaded) and ran
        // this program
        // (in other words, when you run this program, what does it print?
        // Copy that output into this file, right here, in a comment
        //  Hello from lecture 01
        //PS C:\Users\josia> 

        

        // Put your answer for #2 here:
       for (int i = 1; i <= 100; i++) {
            System.out.println(i);
        }
    
        // Where in the textbook are the main topics for this question covered?
        // You can find this in chpater 2.1 about tracing loops and nested loops

        // Put your answer for #3 here:
         for (int i = 1; i <= 5; i++) {
            // Inner loop for printing asterisks
            for (int j = 1; j <= i; j++) {
                System.out.print("*");
            }
            // Move to the next line after each row is printed
            System.out.println();
        }
    



        // Where in the textbook are the main topics for this question covered?
        // You can find this in chpater 2.1 about tracing loops and nested loops

        // Put your answer for #4 here:
         System.out.print("Enter the number of rows: ");
         int numRows = scanner.nextInt();

     

        for (int i = 0; i < numRows; i++) {
            // Inner loop for printing asterisks
            for (int j = 0; j <= i; j++) {
                System.out.print(j+" ");
            }
            // Move to the next line after each row is printed
            System.out.println();
        }
    

        // Where in the textbook are the main topics for this question covered?
        // You can find this in chapter 2.4 complex loops

        // Put your answer for #5 here:
        System.out.print("How many grades would you like to store ");
         int numGrades = scanner.nextInt();
         double sum = 0.0;

        for (int i = 1; i <= numGrades; i++) {
            System.out.print("Next grade? ");
            double grade = scanner.nextDouble();
            sum += grade;
        }
        
        double average = sum / numGrades;
        System.out.println("The average of your grades is " + average);
        System.out.println();
        System.out.println("Self-Check Activity #6: Food Options using Object-Oriented Programming");
        FoodOption wings = new FoodOption("Wings", 55, 4.5);
        FoodOption pizza = new FoodOption("Pizza", 150, 4.8);

        System.out.println("Food Options:");
        wings.print();
        pizza.print();
    }
}
        // Where in the textbook are the main topics for this question covered?
        // You can find this in chapter 2.4 complex loops




        // Put your answer for #6 here:
        // Where in the textbook are the main topics for this question covered?

        // NOTE: The definition of the Food class should go OUTSIDE the Lecture01
        // class. A good place to put this is at the end of the file.
        // NOTE 2: Make sure that you create a couple of Food objects here in main()

    
    



// Placing the Food class below this line is a good place for it
class FoodOption {
    private String name;
    private int calories;
    private double rating;

    public FoodOption(String name, int calories, double rating) {
        this.name = name;
        this.calories = calories;
        
        // Ensure rating is within the range [0, 5]
        if (rating >= 0 && rating <= 5) {
            this.rating = rating;
        } else {
            this.rating = 0;
        }
    }

    public void print() {
        System.out.println("Food: " + name);
        System.out.println("Calories: " + calories);
        System.out.println("Rating: " + rating);
    }
}